name: First Workflow

on: workflow_dispatch

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4
          
          - name: Welcome message
            run: echo "Hello Serhii"
          
          - name: Check files
            run: ls -al

          - name: Print the test.txt file
            run: cat test.txt